title: Streamdata Gallery Microsoft Office 365
url: microsoft-office-365.streamdata.gallery
tag: Microsoft Office 365
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery
github_repo: microsoft-office-365
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
